#!/bin/sh
# Bootstrap helper for the Homebrew tap repository
# (ivankuznetsov/homebrew-tap).  Run this once locally before the first
# tag push — it creates the minimal skeleton the release workflow's
# `update-tap` job needs to push into.
#
# Usage:
#   packaging/bootstrap-tap.sh ../homebrew-tap
set -eu

TARGET="${1:?usage: $0 <path-to-tap-checkout>}"

if [ ! -d "$TARGET" ]; then
  echo "Creating tap directory at $TARGET"
  mkdir -p "$TARGET"
  cd "$TARGET"
  git init
  cd - >/dev/null
fi

mkdir -p "$TARGET/Formula"

# Seed Formula/xbookmark.rb with a stub that the CI render step will
# overwrite on the first promoted release.  Without this seed file,
# `update-tap` may fail on a fresh tap repo on some `sed` versions.
cat > "$TARGET/Formula/xbookmark.rb" <<'STUB'
# Auto-generated by xbookmark release workflow on first promoted release.
class Xbookmark < Formula
  desc "Sync X (Twitter) bookmarks into a local Obsidian-ready bookmark wiki"
  homepage "https://github.com/ivankuznetsov/xbookmark"
  version "0.0.0"
  license "MIT"
  url "https://example.invalid"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  def install; end
end
STUB

cat > "$TARGET/README.md" <<'README'
# Homebrew tap for xbookmark

Install with:

```
brew install ivankuznetsov/tap/xbookmark
```

The formula in `Formula/xbookmark.rb` is rewritten automatically by
the xbookmark release workflow.  Do not edit it by hand.
README

echo "Tap skeleton ready at $TARGET."
echo "Next steps:"
echo "  1. Commit + push to ivankuznetsov/homebrew-tap on GitHub."
echo "  2. Add a deploy key with write access and store the private half"
echo "     as the HOMEBREW_TAP_DEPLOY_KEY secret on the xbookmark repo."
